In [7]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN
import matplotlib as plt
import os
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import GroupKFold
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import R2Score, RootMeanSquaredError

colab = False

In [8]:
dataset_path = os.getcwd()

if colab:
  dataset_path = os.path.join(dataset_path, os.listdir(dataset_path)[1])
else:
  # print(dataset_path)
  dataset_path = os.path.join(dataset_path, "Final_Dataset")
  # print(os.listdir(dataset_path))
  dataset_path = os.path.join(dataset_path, os.listdir(dataset_path)[0])
print(dataset_path)

data = pd.read_csv(dataset_path)
# print(data)
X = data.iloc[:, 0:data.shape[1]-1].values
# print(X)
y = data.iloc[:, data.shape[1]-1].values

c:\Users\nwalr\OneDrive - Georgia Institute of Technology\VIP\TreatmentSystems\Final_Dataset\concatenated_data.csv


### Create the Model Implementation

Input Layer: __ neurons
Hidden Layers:
Output Layer:

#### Resources:
1. https://www.tensorflow.org/guide/keras/working_with_rnns
2. https://www.tensorflow.org/guide/keras/transfer_learning
3. https://machinelearningmastery.com/understanding-simple-recurrent-neural-networks-in-keras/
4. https://keras.io/api/models/sequential/
5. https://medium.com/@researchgraph/beginners-guide-to-recurrent-neural-networks-rnns-with-keras-7b8eb408caa1

In [9]:
LR = 0.01

In [10]:
# ##Without Min_Max Scalar

# groupKFold = GroupKFold(n_splits = 5)
# groups = X[:, 0]
# r2_scores, rmse_vals = [], []
# # Apply splits while ensuring patient grouping is maintained
# split_num = 1
# for train_index, test_index in groupKFold.split(data, groups = groups):
#     X_train, X_test = X[train_index], X[test_index]
#     y_train, y_test = y[train_index], y[test_index]

    
#     model = Sequential()
#     model.add(Dense(50, activation = "relu", input_dim = X_train.shape[1]))
#     model.add(Dense(25, activation = "relu", input_dim = X_train.shape[1]))
#     model.add(Dense(1, activation = "linear"))
#     model.compile(optimizer = Adam(0.01), loss = RootMeanSquaredError(), metrics = R2Score())
#     history = model.fit(X_train, y_train, epochs = 200)
#     loss, mae = model.evaluate(X_test, y_test)

#     print(loss)
#     print(mae)

#     # print(f"Split Num: {split_num}")
#     # print(f"R2 Score: {r2}")
#     # print(f"RMSE: {np.sqrt(mse)}")
#     # print(f"Y_PRED: {y_pred}")
#     # r2_scores.append(r2)
#     # rmse_vals.append(np.sqrt(mse))
#     split_num += 1

In [14]:
##Using MinMaxScalar for Standardization
scaler = MinMaxScaler()

##Overall there are 25 groups since there are 25 patient IDs
groupKFold = GroupKFold(n_splits = 5)
groups = X[:, 0]
min_max_r2_scores, min_max_rmse_vals = [], []
# Apply splits while ensuring patient grouping is maintained
split_num = 1
for train_index, test_index in groupKFold.split(data, groups = groups):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # print(f"Unique classes in TRAIN: {np.unique(X_train[:,0])}")
    # print(f"Unique classes in TEST: {np.unique(X_test[:,0])}")
    # print(f"TRAIN shapes: X: {X_train.shape}, y: {y_train.shape}")
    # print(f"TEST shapes: X: {X_test.shape}, y: {y_test.shape}")

    X_train_cyclical, X_test_cyclical = X_train[:, 1:3], X_test[:, 1:3]
    X_train_sleep, X_test_sleep = X_train[:, -1:], X_test[:, -1:]
    print(X_train_sleep, X_train_sleep.shape)
    print(X_test_sleep, X_test_sleep.shape)
    # # print(X_train_cyclical)
    # # print(X_test_cyclical)
    # X_train, X_test = X_train[:, 3:], X_test[:, 3:]
    # # print(X_train)
    # # print(X_test)

    # scaled_X_train = scaler.fit_transform(X_train)
    # scaled_X_test = scaler.transform(X_test)

    # scaled_X_train = np.concatenate((X_train_cyclical, scaled_X_train), axis = 1)
    # scaled_X_test = np.concatenate((X_test_cyclical, scaled_X_test), axis = 1)
    # # print("X_train = ", scaled_X_train)
    # # print("X_test = ", scaled_X_test)

    # svr_model.fit(scaled_X_train, y_train)

    # y_pred = svr_model.predict(scaled_X_test)

    # r2 = r2_score(y_test, y_pred)
    # mse = mean_squared_error(y_test, y_pred)
    # print(f"Split Num: {split_num}")
    # print(f"R2 Score: {r2}")
    # print(f"RMSE: {np.sqrt(mse)}")
    # print(f"Y_PRED: {y_pred}")
    # min_max_r2_scores.append(r2)
    # min_max_rmse_vals.append(np.sqrt(mse))
    # split_num += 1

[[0.10833333]
 [0.10833333]
 [0.10833333]
 ...
 [0.        ]
 [0.        ]
 [0.        ]] (71452, 1)
[[0.09166667]
 [0.09166667]
 [0.09166667]
 ...
 [0.152     ]
 [0.152     ]
 [0.152     ]] (18226, 1)
[[0.09166667]
 [0.09166667]
 [0.09166667]
 ...
 [0.        ]
 [0.        ]
 [0.        ]] (71737, 1)
[[0.0475]
 [0.0475]
 [0.0475]
 ...
 [0.    ]
 [0.    ]
 [0.    ]] (17941, 1)
[[0.09166667]
 [0.09166667]
 [0.09166667]
 ...
 [0.        ]
 [0.        ]
 [0.        ]] (71861, 1)
[[0.06916667]
 [0.06916667]
 [0.06916667]
 ...
 [0.        ]
 [0.        ]
 [0.        ]] (17817, 1)
[[0.09166667]
 [0.09166667]
 [0.09166667]
 ...
 [0.        ]
 [0.        ]
 [0.        ]] (71888, 1)
[[0.075]
 [0.075]
 [0.075]
 ...
 [0.   ]
 [0.   ]
 [0.   ]] (17790, 1)
[[0.09166667]
 [0.09166667]
 [0.09166667]
 ...
 [0.        ]
 [0.        ]
 [0.        ]] (71774, 1)
[[0.10833333]
 [0.10833333]
 [0.10833333]
 ...
 [0.13333333]
 [0.13333333]
 [0.13333333]] (17904, 1)


### Metrics Analysis of Created Model

#### Resources:
1. https://keras.io/api/metrics/regression_metrics/#r2score-class
2. https://keras.io/api/metrics/regression_metrics/#rootmeansquarederror-class

### Create the Visualizations of the Loss Plot