In [56]:
import numpy as np
import pandas as pd

# from sklearn.model_selection import
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler
from sklearn.svm import SVR
from sklearn.compose import ColumnTransformer
from sklearn.metrics import r2_score, mean_squared_error

import matplotlib.pyplot as plt

import os

#Running on Google Colab = True/locally = False
colab = False

## Mounting to Google Drive

### Uncomment if utilizing Google Colab

In [10]:
if colab:
    from google.colab import drive 
    drive.mount('/content/drive')

    %cd "/content/drive/My Drive/TreatmentSystems"

In [11]:
dataset_path = os.getcwd()
dataset_path

'c:\\Users\\nwalr\\OneDrive - Georgia Institute of Technology\\VIP\\TreatmentSystems'

In [ ]:
dataset_path = os.path.join(dataset_path, 'Final_Dataset/Filtered_Data/HUPA0001P.csv')
data = pd.read_csv(dataset_path)
X = data.iloc[:, 0:data.shape[1]-1].values
# print(X)
y = data.iloc[:, data.shape[1]-1].values
# print(y)

[[-9.84807753e-01  1.73648178e-01  8.23228347e+01  3.40000000e+01
   9.16666670e-02  0.00000000e+00]
 [-9.80785280e-01  1.95090322e-01  8.37401575e+01  0.00000000e+00
   9.16666670e-02  0.00000000e+00]
 [-9.76296007e-01  2.16439614e-01  8.05251799e+01  0.00000000e+00
   9.16666670e-02  0.00000000e+00]
 ...
 [-6.54031292e-02  9.97858923e-01  7.93589744e+01  0.00000000e+00
   5.83333330e-02  0.00000000e+00]
 [-4.36193874e-02  9.99048222e-01  8.20583333e+01  0.00000000e+00
   5.83333330e-02  0.00000000e+00]
 [-2.18148850e-02  9.99762027e-01  8.75510204e+01  0.00000000e+00
   5.83333330e-02  0.00000000e+00]]
[332. 326. 330. ... 327. 326. 326.]


In [ ]:
train_size = int(len(X) * 0.7)
test_size = int(len(X) - train_size)
X_train, X_test = np.array(X[:train_size]), np.array(X[train_size:])
y_train, y_test = np.array(y[:train_size]), np.array(y[train_size:])
# print(len(X_train))
# print(X_train[-5:])
# print(X_test[:5])

2867
[[-0.97629601 -0.21643961 85.60344828  0.          0.09166667  0.        ]
 [-0.98078528 -0.19509032 84.504       0.          0.09166667  0.        ]
 [-0.98480775 -0.17364818 84.0620155   0.          0.09166667  0.        ]
 [-0.98836151 -0.15212339 85.73684211  0.          0.09166667  0.        ]
 [-0.99144486 -0.13052619 84.83870968  0.          0.09166667  0.        ]]
[[-9.94056338e-01 -1.08866875e-01  8.68695652e+01  0.00000000e+00
   9.16666670e-02  0.00000000e+00]
 [-9.96194698e-01 -8.71557427e-02  8.42000000e+01  1.00000000e+01
   9.16666670e-02  0.00000000e+00]
 [-9.97858923e-01 -6.54031292e-02  8.55258621e+01  0.00000000e+00
   9.16666670e-02  0.00000000e+00]
 [-9.99048222e-01 -4.36193874e-02  8.42047244e+01  0.00000000e+00
   9.16666670e-02  0.00000000e+00]
 [-9.99762027e-01 -2.18148850e-02  8.51360000e+01  0.00000000e+00
   9.16666670e-02  0.00000000e+00]]


In [ ]:
svr_model1 = SVR(kernel='rbf')
svr_model1.fit(X_train, y_train)

y_pred = svr_model1.predict(X_test)

print("Sample of Target")
print(y_test[:10])

print("Sample of Predictions")
print(y_pred[:10])

r2 = r2_score(y_test, y_pred)
print("R2 = ", r2)
mse = mean_squared_error(y_test, y_pred)
print("MSE = ", mse)

Sample of Target
[158. 154. 154. 153. 152. 150. 151. 150. 153. 148.]
Sample of Predictions
[168.99176153 167.31749557 167.86879275 166.75855402 167.54151526
 168.22384096 168.60350649 168.92136291 169.9762634  167.72604169]
R2 =  -0.036424611518330874
MSE =  3765.441353198703


In [ ]:
column_names = data.columns
print(column_names[:2])
print(column_names[2:data.shape[1] - 1])
standardize_features = column_names[2:data.shape[1] - 1] # Features to standardize
passthrough_features = column_names[:2]  # Keep these unchanged

# Define ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('passthrough', 'passthrough', passthrough_features), 
        ('standardize', MinMaxScaler(), standardize_features)  # Apply MinMaxScaler
    ]
)

# Apply transformation
X_train_scaled = preprocessor.fit_transform(data[:train_size])
X_test_scaled = preprocessor.transform(data[train_size:])

X_train_scaled = np.array(X_train_scaled)
X_test_scaled = np.array(X_test_scaled)

# Display first few rows
print(X_train_scaled[-5:])

print(X_test_scaled[:5])

svr_model1.fit(X_train_scaled, y_train)

y_pred = svr_model1.predict(X_test_scaled)

print("Sample of Target")
print(y_test[:10])

print("Sample of Predictions")
print(y_pred[:10])

r2 = r2_score(y_test, y_pred)
print("R2 = ", r2)
mse = mean_squared_error(y_test, y_pred)
print("MSE = ", mse)

Index(['time_sin', 'time_cos'], dtype='object')
Index(['heart_rate', 'steps', 'basal_rate', 'bolus_volume_delivered'], dtype='object')
[[-0.97629601 -0.21643961  0.28228601  0.          1.          0.        ]
 [-0.98078528 -0.19509032  0.27262989  0.          1.          0.        ]
 [-0.98480775 -0.17364818  0.26874808  0.          1.          0.        ]
 [-0.98836151 -0.15212339  0.28345756  0.          1.          0.        ]
 [-0.99144486 -0.13052619  0.27556954  0.          1.          0.        ]]
[[-0.99405634 -0.10886687  0.29340592  0.          1.          0.        ]
 [-0.9961947  -0.08715574  0.26995995  0.01610306  1.          0.        ]
 [-0.99785892 -0.06540313  0.28160459  0.          1.          0.        ]
 [-0.99904822 -0.04361939  0.27000144  0.          1.          0.        ]
 [-0.99976203 -0.02181489  0.27818055  0.          1.          0.        ]]
Sample of Target
[158. 154. 154. 153. 152. 150. 151. 150. 153. 148.]
Sample of Predictions
[204.02088956 204.0150

In [59]:
preprocessor2 = ColumnTransformer(
    transformers=[
        ('passthrough', 'passthrough', passthrough_features), 
        ('standardize', RobustScaler(), standardize_features)  # Apply MinMaxScaler
    ]
)

# Apply transformation
X_train_scaled = preprocessor2.fit_transform(data[:train_size])
X_test_scaled = preprocessor2.transform(data[train_size:])

X_train_scaled = np.array(X_train_scaled)
X_test_scaled = np.array(X_test_scaled)

# Display first few rows
print(X_train_scaled[-5:])

print(X_test_scaled[:5])

svr_model1.fit(X_train_scaled, y_train)

y_pred = svr_model1.predict(X_test_scaled)

print("Sample of Target")
print(y_test[:10])

print("Sample of Predictions")
print(y_pred[:10])

r2 = r2_score(y_test, y_pred)
print("R2 = ", r2)
mse = mean_squared_error(y_test, y_pred)
print("MSE = ", mse)

[[-0.97629601 -0.21643961  0.31875614  0.          1.50000002  0.        ]
 [-0.98078528 -0.19509032  0.2639208   0.          1.50000002  0.        ]
 [-0.98480775 -0.17364818  0.24187668  0.          1.50000002  0.        ]
 [-0.98836151 -0.15212339  0.3254092   0.          1.50000002  0.        ]
 [-0.99144486 -0.13052619  0.28061455  0.          1.50000002  0.        ]]
[[-0.99405634 -0.10886687  0.38190413  0.          1.50000002  0.        ]
 [-0.9961947  -0.08715574  0.2487587   1.66666667  1.50000002  0.        ]
 [-0.99785892 -0.06540313  0.3148865   0.          1.50000002  0.        ]
 [-0.99904822 -0.04361939  0.24899433  0.          1.50000002  0.        ]
 [-0.99976203 -0.02181489  0.295442    0.          1.50000002  0.        ]]
Sample of Target
[158. 154. 154. 153. 152. 150. 151. 150. 153. 148.]
Sample of Predictions
[173.96331371 175.16150184 173.65279274 173.34958849 173.5491932
 173.72083522 173.81012774 173.88129342 174.14966788 173.528022  ]
R2 =  -0.0537099069482052

In [ ]:
preprocessor3 = ColumnTransformer(
    transformers=[
        ('passthrough', 'passthrough', passthrough_features), 
        ('standardize', StandardScaler(), standardize_features)
    ]
)

# Apply transformation
X_train_scaled = preprocessor2.fit_transform(data[:train_size])
X_test_scaled = preprocessor2.transform(data[train_size:])

X_train_scaled = np.array(X_train_scaled)
X_test_scaled = np.array(X_test_scaled)

# Display first few rows
print(X_train_scaled[-5:])

print(X_test_scaled[:5])

svr_model1.fit(X_train_scaled, y_train)

y_pred = svr_model1.predict(X_test_scaled)

print("Sample of Target")
print(y_test[:10])

print("Sample of Predictions")
print(y_pred[:10])

r2 = r2_score(y_test, y_pred)
print("R2 = ", r2)
mse = mean_squared_error(y_test, y_pred)
print("MSE = ", mse)

[[-0.97629601 -0.21643961  0.31875614  0.          1.50000002  0.        ]
 [-0.98078528 -0.19509032  0.2639208   0.          1.50000002  0.        ]
 [-0.98480775 -0.17364818  0.24187668  0.          1.50000002  0.        ]
 [-0.98836151 -0.15212339  0.3254092   0.          1.50000002  0.        ]
 [-0.99144486 -0.13052619  0.28061455  0.          1.50000002  0.        ]]
[[-0.99405634 -0.10886687  0.38190413  0.          1.50000002  0.        ]
 [-0.9961947  -0.08715574  0.2487587   1.66666667  1.50000002  0.        ]
 [-0.99785892 -0.06540313  0.3148865   0.          1.50000002  0.        ]
 [-0.99904822 -0.04361939  0.24899433  0.          1.50000002  0.        ]
 [-0.99976203 -0.02181489  0.295442    0.          1.50000002  0.        ]]
Sample of Target
[158. 154. 154. 153. 152. 150. 151. 150. 153. 148.]
Sample of Predictions
[173.96331371 175.16150184 173.65279274 173.34958849 173.5491932
 173.72083522 173.81012774 173.88129342 174.14966788 173.528022  ]
R2 =  -0.0537099069482052

## Attempting a Different Kernel Type

## HyperTuning SVR